services:
  flightfinder:
    build: .
    restart: always
    environment:
      - SMTP_HOST=smtp
      - SMTP_PORT=25
      - SENDER_EMAIL=flights@flightfinder.local
    volumes:
      - ./trips.csv:/app/trips.csv
    depends_on:
      - smtp

  smtp:
    image: namshi/smtp
    restart: always
